### PR TITLE
Add Linux installation guide

### PR DESCRIPTION
**Pull request by lilafian**
This pull request adds a guide to the README.md file for Linux users as the file may not open when run without following the steps.

### CODE REVIEW

**Review by SwiftDust — COMMENTED** [review]
Nice, but you could maybe then make a full **Installation** section or even an INSTALL.md file

**Comment by lilafian** [comment]
good idea, doing now!!!!!!

**Comment by lilafian** [comment]
totally didnt accidentally open a pr into my fork....

**Comment by lilafian** [comment]
has better wording now i think

**Review by SwiftDust — APPROVED** [review]
LGTM! :tada: 
Adding appropriate tags and merging it now
-ThatFrogDev

**Pull request merged**
