### PR TITLE
Fixed multiple issues + convenience

### LINKED ISSUE #13: BUG ・ `notes.db` creates in the working directory
## Are you facing this issue using Notabena CLI or Desktop?
[ ] CLI
_(as of now, only possible answer)_

## On what platform are you facing the bug?
[ ] Windows 10 or later
[ ] Other Windows
[ ] macOS
[ ] Ubuntu
[ ] Other Linux

## Describe the bug:
The `notes.db` file creates in the folder you run it in, instead of in a general AppData directory or similar.

## How to reproduce the error?
1. Run `cargo r` or `notabena` in any directory
2. Exit the program and see the `ls output` It shows a `notes.db` file.
3. `cd` into another directory
4. Reproduce steps 1 and 2

## Expected behavior
It should create the database file in a general data directory, like `AppData/notabena` or `.notabena`

## Screenshots
_(not required)_ Could you send any screenshots to help us understand and reproduce the error?

## Anything to add?
**Note from the developer:** We didn't design the code for this correctly, but we only realized now. We know how to fix the bug and we're going to patch it as soon as possible.

### LINKED ISSUE #15: FRQ • About menu
### Is this a fix to a problem or just a new feature that you'd like to see?

new feature

### For what problem is your feature a fix?

its a feature to fix people not keeping track of what version they have, being able to admire the contrubutors, etc

### What is the solution or feature?

add the about section to Notabena, which consists of the version, (possibly: change log) and main contributors

### PR DESCRIPTION
**Pull request by SwiftDust**
## Description
See changelog for detailed information. Co-authors: @MrSerge01 

### Major Changes
- About menu
- The database file gets created in the OS's `config` directory
### Minor Changes
- Formatted and simplified code

This pull request fixes: #13 and #15

### CODE REVIEW

**Comment by MrSerge01** [comment]
how can i review lol its a draft

**Comment by SwiftDust** [comment]
> how can i review lol its a draft

Just wait for the magic to happen 😌

**Review by MrSerge01 — COMMENTED** [review]
LGTM! good work from both of us, literally returned home and the next day done this.
\- The Goos.

**Review by MrSerge01 — APPROVED** [review]
meant to approve

**Pull request merged**
